### PR TITLE
fix: wrong hover detection with scrollbar

### LINKED ISSUE #118: Tooltip with hover trigger not working on page with scrollbar
**Describe the bug**
When mouse enters trigger element and page has vertical scrollbar and his position is not at top of page then tooltip is flickering and does not remain visible. Problem is probably with function `mouseOutsideRect` and comparing mouse and trigger position: `(pageY || clientY) < Math.floor(top) || (pageY || clientY) > Math.ceil(bottom)`.

**To Reproduce**
https://codesandbox.io/s/white-leaf-094it?file=/src/index.js
https://user-images.githubusercontent.com/18634735/108426708-613e2900-723c-11eb-924b-b7b9096d97dc.mov

**Expected behavior**
Tooltip should remain visible after hover button.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 88

### PR DESCRIPTION
**Pull request by czabaj**
Use `clientX,Y` from `MouseEvent` instead `pageX,Y`

fixes #118

### CODE REVIEW

**Comment by czabaj** [comment]
Well, that was easy. Sad that these changes are so hard to test.

File: src/utils.ts [hunk 1]
```diff
@@ -64,15 +64,15 @@ export function generateBoundingClientRect(x = 0, y = 0) {
...
+  { clientX, clientY }: MouseEvent,
   { bottom, left, right, top }: DOMRect
 ) =>
   // DOMRect contains fractional pixel values but MouseEvent reports integers,
   // so we round DOMRect boundaries to make DOMRect slightly bigger
-  (pageX || clientX) < Math.floor(left) ||
-  (pageX || clientX) > Math.ceil(right) ||
-  (pageY || clientY) < Math.floor(top) ||
-  (pageY || clientY) > Math.ceil(bottom);
+  clientX < Math.floor(left) ||
```
Comment (mohsinulhaq) [inline src/utils.ts:72]: was there any reason you were using pageX first?

Comment (czabaj) [reply src/utils.ts:72]: @mohsinulhaq I misunderstood the documentation and thought that `pageX,Y` reports the right position, but I digged deeper and found out, that `pageX,Y` is [relative to edge of the document and it takes into account any scrolled invisible space](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/pageX), but the `clientX,Y` is precisely what I need, as it [reports position relative to the viewport](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX), where `getBoundingClientRect` returns [also positions relative to the viewport](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect).

**Review by mohsinulhaq — APPROVED** [review]
