### PR TITLE
fix: tooltip appears unintended with `delayShow`

### LINKED ISSUE #117: Tooltip appears even after mouse leaves the trigger
Even if the mouse is not hovering over the trigger element, the tooltip will still appear.

1. Go to the basic example ([here](https://codesandbox.io/s/github/mohsinulhaq/react-popper-tooltip/tree/master/examples/basic?file=/src/index.js))
2. Modify the code to pass { delayShow: 1000 } to usePopperTooltip
3. Hover over the button, then move the cursor away and stop moving it
4. The tooltip still appears, and will stay until the mouse moves again

Ideally, the tooltip should not appear, but it does probably because of the changes in #115 

image

Windows 10
Chrome, Edge
Latest

### PR DESCRIPTION
**Pull request by czabaj**
Clear the `showTooltip` timeout on `mouseleave`.
Also fix the potential memory leak with wrong `useEffect` call.
And improve Storybook story to allow simulate various `offset`.

fixes #117

### CODE REVIEW

File: src/usePopperTooltip.ts [hunk 1]
```diff
@@ -69,6 +69,8 @@ export function usePopperTooltip(
   });
 
   const timer = React.useRef<number>();
+  const stopTimer = React.useCallback(() => clearTimeout(timer.current), []);
+  React.useEffect(() => stopTimer, [stopTimer]);
```
Comment (czabaj) [inline src/usePopperTooltip.ts:73]: Create `stopTimer` callback to ease event handler register/unregister.

The `useEffect` was moved from the bottom, I believe it shall clear the timeout on _unmount_ to prevent memory leak, but it was written

```JavaScript
React.useEffect(() => clearTimeout(timer.current), []);
```

Which clears the timeout _onMount_ only.

Am I right?

File: src/usePopperTooltip.ts [hunk 2]
```diff
@@ -185,10 +185,16 @@ export function usePopperTooltip(
...
 
     triggerRef.addEventListener('mouseenter', showTooltip);
+    if (!visible) {
+      triggerRef.addEventListener('mouseleave', stopTimer);
+    }
     return () => {
       triggerRef.removeEventListener('mouseenter', showTooltip);
+      if (!visible) {
+        triggerRef.removeEventListener('mouseleave', stopTimer);
+      }
```
Comment (czabaj) [inline src/usePopperTooltip.ts:195]: Until visible, the `mouseleave` stops the timer.

File: stories/basic.stories.tsx [hunk 3]
```diff
@@ -59,6 +64,12 @@ Example.argTypes = {
       type: 'boolean',
     },
   },
+  offsetDistance: {
+    control: {
+      type: 'number',
+      options: { min: 0, step: 1 },
+    },
+  },
```
Comment (czabaj) [inline stories/basic.stories.tsx:72]: Added control to test various offsets.

File: stories/basic.stories.tsx [hunk 4]
```diff
@@ -3,7 +3,11 @@ import { Story, Meta } from '@storybook/react';
 import { usePopperTooltip, Config } from '../src';
 import '../src/styles.css';
 
-export const Example: Story<Config> = (props) => {
+export const Example: Story<Config & { offsetDistance?: number }> = ({
+  // eslint-disable-next-line react/prop-types
+  offsetDistance = 6,
```
Comment (czabaj) [inline stories/basic.stories.tsx:8]: I suppressed this complaint. The `Example` component has no `propTypes` so I believe it is cleaner without it.

**Comment by czabaj** [comment]
@mohsinulhaq just a side note. I think the logic could be simplified if we introduce another state for the `visible` state that is set even not yet applied (because of the delays). Something like

```
const [visible, setVisible] = useState(initialVisible)
const [visibleSync, setVisibleSync] = useState(initialVisible)
// single useEffect handles all the asynchrony
useEffect(() => {
  timer.current = window.setTimeout(
    () => setVisible(visibleSync),
    visibleSync ? finalConfig.delayShow : finalConfig.delayHide)
  )
  return () => window.clearTimeout(timer.current)
}, [visibleSync])
```

and then the `mousemove` handler can also be simplified. It now must remember such a `visibleSync` with local variable `lastMouseOutside`, but the `mousemove` could simply unregistered once the `visibleSync` is `false` and register when `visibleSync` is `true` which will fix all problems originating from reliance on `visible` state, which can be daleyed.

This is but more complicated refactoring and I would like to discuss it here (or somewhere else) for a later attempt to implement it. It could have many problems which I don't see just now.

File: stories/basic.stories.tsx (hunk 4 above)
Comment (mohsinulhaq) [reply stories/basic.stories.tsx:8]: you would need to do this to avoid it

```ts
type ExampleProps = Config & { offsetDistance?: number }

export const Example: Story<ExampleProps> = ({...}: ExampleProps) => {
```

also, you should move the default offsetDistance value from here to bottom config
see the comment below

File: stories/basic.stories.tsx [hunk 5]
```diff
@@ -59,6 +64,12 @@ Example.argTypes = {
       type: 'boolean',
     },
   },
+  offsetDistance: {
```
Comment (mohsinulhaq) [inline stories/basic.stories.tsx:67]: add `defaultValue: 6` here

File: src/usePopperTooltip.ts (hunk 1 above)
Comment (mohsinulhaq) [reply src/usePopperTooltip.ts:73]: not sure what was why it was done on mount, @denisborovikov was this intentional?

File: src/usePopperTooltip.ts [hunk 6]
```diff
@@ -69,6 +69,8 @@ export function usePopperTooltip(
   });
 
   const timer = React.useRef<number>();
+  const stopTimer = React.useCallback(() => clearTimeout(timer.current), []);
```
Comment (mohsinulhaq) [inline src/usePopperTooltip.ts:72]: I dont think this is required, since its not passed to any component for it to change reference
just clearTimeout(timer.current) all over the place

**Review by mohsinulhaq — CHANGES_REQUESTED** [review]

File: src/usePopperTooltip.ts (hunk 1 above)
Comment (czabaj) [reply src/usePopperTooltip.ts:73]: Checked again. The `timer` is used only in `{hide,show}Tooltip` callbacks. These are not called initially but on events. There is no need to clear the timeout on _mount_, but if some component sets the timeout, which performs `setState` or whatever, it _must_, as a rule of thumb, clear the timeout on `unMount` which you do by return a cleanup function from the `useEffect`.

It is very common to forget to wrap it in one more function, it was 

```JavaScript
React.useEffect(() => clearTimeout(timer.current), []);
```

but shall be 

```JavaScript
React.useEffect(() => () => clearTimeout(timer.current), []);
```

which is equivalent to

```JavaScript
React.useEffect(() => stopTimer, []);
```

File: stories/basic.stories.tsx (hunk 4 above)
Comment (czabaj) [reply stories/basic.stories.tsx:8]: Nope. I managed to satisfy TypeScript compiler, this is an ESLint error. Like, really.

Comment (mohsinulhaq) [reply stories/basic.stories.tsx]: I actually tried it. It does fix the ESlint error. Can you try it out?

Comment (czabaj) [reply stories/basic.stories.tsx]: Does not work on my machine 😕 I even restarted the IDE to assure, that ESLint does not cache the error.
Screenshot 2021-02-20 at 9 55 15

File: src/usePopperTooltip.ts (hunk 6 above)
Comment (czabaj) [reply src/usePopperTooltip.ts:72]: I pass the handler to `triggerRef.addEventListener('mouseleave', stopTimer);` and I though it will be convenient to have single reference of the function to simplify `removeEventListener` but actually, this ha a bug, as `useCallback` (as well as `useMemo`) does not guarantee the single reference will ever be created. It is just performance hint and the reference can be removed by GC (sounds like React uses WekMaps for this under the hood). I will inline the logic to places, where needed.

File: stories/basic.stories.tsx (hunk 4 above)
Comment (mohsinulhaq) [reply stories/basic.stories.tsx]: @czabaj you haven't applied the ExampleProps to the component props :)

File: src/usePopperTooltip.ts (hunk 6 above)
Comment (mohsinulhaq) [reply src/usePopperTooltip.ts]: oh yes, i missed that you used it for removing the listener
although now it looks a bit uglier
instead of stopTimer being either a boolean or a function, can you just create the function directly and use the isvisible check to add/remove stopTimer, preferably with an if statement, instead of a conditional

Comment (czabaj) [reply src/usePopperTooltip.ts]: I agree that hacking short circuits for "if statement" is ugly. But if you propose to attach the function always and test the `isVisible` inside it, I would rather not. It is better to not attach the function when the condition falses and there is a problem with function reference, that I must keep, to be able to unregister the listener later. I can rewrite this to if statement, but the `boolean | function` variable type does more good than harm IMHO.

Comment (denisborovikov) [reply src/usePopperTooltip.ts]: @mohsinulhaq I don't remember I had an intention to clear the timer on mount, pretty sure it should be on unmount to avoid any related state changes when the component already unmounted.

File: src/usePopperTooltip.ts [hunk 7]
```diff
@@ -185,10 +184,13 @@ export function usePopperTooltip(
     if (triggerRef == null || !isTriggeredBy('hover')) return;
 
     triggerRef.addEventListener('mouseenter', showTooltip);
+    const stopTimer = !visible && (() => clearTimeout(timer.current));
+    stopTimer && triggerRef.addEventListener('mouseleave', stopTimer);
     return () => {
       triggerRef.removeEventListener('mouseenter', showTooltip);
+      stopTimer && triggerRef.removeEventListener('mouseleave', stopTimer);
     };
```
Comment (mohsinulhaq) [inline src/usePopperTooltip.ts:192]:
```suggestion
    let stopTimer: any;
    if (!visible) {
      stopTimer = () => clearTimeout(timer.current);
      triggerRef.addEventListener('mouseleave', stopTimer);
    }
    return () => {
      triggerRef.removeEventListener('mouseenter', showTooltip);
      triggerRef.removeEventListener('mouseleave', stopTimer);
    };
```
how about this?

Comment (czabaj) [reply src/usePopperTooltip.ts]: Rewrote to if statement 😒

File: src/usePopperTooltip.ts [hunk 8]
```diff
@@ -184,11 +184,16 @@ export function usePopperTooltip(
...
-    stopTimer && triggerRef.addEventListener('mouseleave', stopTimer);
+    let stopTimer: undefined | (() => void);
+    if (!visible) {
+      stopTimer = () => clearTimeout(timer.current);
+      triggerRef.addEventListener('mouseleave', stopTimer);
+    }
     return () => {
       triggerRef.removeEventListener('mouseenter', showTooltip);
-      stopTimer && triggerRef.removeEventListener('mouseleave', stopTimer);
+      if (stopTimer) {
```
Comment (mohsinulhaq) [inline src/usePopperTooltip.ts:194]: this is not really needed, removeEventListener is a noop for undefined callback

Comment (czabaj) [reply src/usePopperTooltip.ts:194]: Yes, but you will make the TypeScript compiler very sad.

Comment (mohsinulhaq) [reply src/usePopperTooltip.ts:194]: oh yes, you're right, totally forgot about TS

**Review by mohsinulhaq — APPROVED** [review]

**Comment by mohsinulhaq** [comment]
@czabaj regarding the alternate `visibleSync` implementation that you proposed, if you want you can take a stab at it and raise a PR, I would be more than happy to get that merged if it simplifies the flow in any way.
